### ISSUE TITLE
Hours is not working in passing dateTime

### ISSUE THREAD

**Issue by sdesikan6** [SparklineData/spark-datetime#1]
import com.github.nscala_time.time.Imports._
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.sparklinedata.spark.dateTime.dsl.expressions._
res319: org.apache.spark.sql.UserDefinedFunction = UserDefinedFunction(<function2>,org.sparklinedata.spark.dateTime.SparkDateTimeUDT@18d9cc82)
dT: org.sparklinedata.spark.dateTime.dsl.DateExpression = org.sparklinedata.spark.dateTime.dsl.package$DateExpression@565f9ece
<console>:194: error: type mismatch;
 found   : com.github.nscala_time.time.DurationBuilder
 required: org.sparklinedata.spark.dateTime.dsl.PeriodExpression
       val dT1 = dateTime('e_log_time) - 8.hours

**Comment by hbutani** [comment]
Fixed. 
Commit is d2adbb12f0a7edb2ad27f90255b36d32d3ff820c
